<a name="loesung07"></a>Lösung Übung 07
===

In [4]:
# 1.a
# importiere sowohl random als auch numpy
# merke: numpy ist von jetzt an mit dem Kürzel "np"
# aufrufbar!
import random
import numpy as np

# erstelle eine Liste mit 100 Zufallszahlen zwischen 0 und 100
numbers = [random.randint(0,101) for i in range(100)]
# konvertiere die Liste in ein Array
numbers = np.asarray(numbers)
# "forme" das eindimensionale Array zu einer zweidimensionalen
# 10x10 Matrix um
numbers = numbers.reshape((10,10))
print(numbers)

[[39 38 57  6 95 98  3 59 80  3]
 [77 12 58 21 38 57 94 65 14 87]
 [23 65 83 44 69 94 38 93 83 44]
 [57 86 26 70 86  9 15 98  5 23]
 [13  3 65 35 12 75 60 71 21 23]
 [ 6 40 32 88 69 51 40 69 33  7]
 [74 29  3 92 92 18 52 83 87 69]
 [45 72 72 48 50 79  8 42 81 56]
 [27 64 61 13  9  6 74 91 43 27]
 [57 86 39  1 14  6 50 31 29 87]]


In [5]:
# 1.b
np.savetxt('zufellige-zahlen.txt', numbers)

In [6]:
# 1.c
# Dokumentation zu numpy.random.randint:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html

numbers = np.random.randint(0, 101, (10,10))
print(numbers)

[[  4   8   9   0  18  71  95   8   0  82]
 [ 48  12  73  20 100  14  44  86  16  58]
 [ 21  27  28  55  76  91  41  42   9   5]
 [ 90  56  32  51  78  78  95  99  69  67]
 [ 24  78  43  35  96   4  13  73  89  90]
 [ 28  79  11  59   2  85  97  98  12  52]
 [ 72  81  42  77  75  11  59  84  95  36]
 [ 37  87   7  53 100  85  31   6  89   5]
 [ 31  78  79  96  31  25  52  62  71  80]
 [ 37  87  88  96  88  34  85  65  84  45]]


In [9]:
# 1.d
print('oben links:')
oben_links = numbers[0:5, 0:5]
print(oben_links)
print('oben rechts')
oben_rechts = numbers[0:5, 5:]
print(oben_rechts)
print('unten links')
unten_links = numbers [5:, 0:5]
print(unten_links)
print('unten rechts')
unten_rechts = numbers[5:, 5:]
print(unten_rechts)

oben links:
[[  4   8   9   0  18]
 [ 48  12  73  20 100]
 [ 21  27  28  55  76]
 [ 90  56  32  51  78]
 [ 24  78  43  35  96]]
oben rechts
[[71 95  8  0 82]
 [14 44 86 16 58]
 [91 41 42  9  5]
 [78 95 99 69 67]
 [ 4 13 73 89 90]]
unten links
[[ 28  79  11  59   2]
 [ 72  81  42  77  75]
 [ 37  87   7  53 100]
 [ 31  78  79  96  31]
 [ 37  87  88  96  88]]
unten rechts
[[85 97 98 12 52]
 [11 59 84 95 36]
 [85 31  6 89  5]
 [25 52 62 71 80]
 [34 85 65 84 45]]


In [11]:
# 1.e
matrix_produkt = np.dot(oben_links, oben_rechts)
print(matrix_produkt)

# etc für die anderen Produkte

[[ 1287  1335  2412  1811  2457]
 [12179 11281 13762 11129 15337]
 [ 9011 10544 14659 11243 13953]
 [14376 18185 17623 11645 21225]
 [ 9823 12048 19179 12594 17692]]


In [14]:
# 1.f
# erstelle eine neue Matrix
# schaue in der Matrix oben_rechts nach:
# wenn oben_rechts > 50, nim ein Element aus unten_links
# wenn oben_rechts < 50, nim ein Element aus unten_rechts
neue_matrix = np.where(oben_rechts > 50, unten_links, unten_rechts)
print(neue_matrix)

[[28 79 98 12  2]
 [11 59 42 95 75]
 [37 31  6 89  5]
 [31 78 79 96 31]
 [34 85 88 96 88]]
