<a name="top"></a>Übersicht: Matrizen
===

* [Matrizen](#matrizen)
  * [Mehrdimensionale Listen](#listen)
  * [NumPy Arrays](#arrays)
  * [Arrays erstellen](#erstellen)
  * [Mathe mit Arrays](#mathe)
  * [Filter](#filter)
* [Übung 07: Matrizen](#uebung07)

**Lernziele:** Am Ende dieser Einheit
* wisst ihr, was eine third party Bibliothek ist und wie ihr sie verwenden könnt
* könnt ihr mehrdimensionalen Daten in Arrays speichern
* könnt einfache Mathe und Filteroperationen auf Arrays ausführen
* könnt Arrays in Dateien speichern und laden

<a name="matrizen"></a>Matrizen
===

Bis jetzt hatten wir es immer nur mit eindimensionalen Datenkontainern zu tun:

In [46]:
liste = [1, 2, 3, 4, 5]

Was tun, wenn wir eine Matrix darstellen wollen?
\begin{equation*}
A = \begin{pmatrix} 1 & 2  & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}
\end{equation*}  

<a name="listen"></a>Mehrdimensionale Listen
---

Im Prinzip könnten wir das mit in Listen verschachtelten Listen realisieren:

In [48]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Auf einzelne Elemente der Liste zugreifen geht noch relativ eifach

In [50]:
print(A[1][1])

5


Aber spätestens wenn wir eine ähnliche Funktionalität wie slicing haben wollten, wird es kompliziert. Zur Erinnerung: bei eindimensionalen Listen funktioniert das slicing so:

In [51]:
a = [1, 2, 3, 4, 5]
print(a[2:4])

[3, 4]


[top](#top)

<a name="arrays"></a>NumPy Arrays
---

[eine umfangreichere Einführung in NumPy findet ihr auf https://docs.scipy.org/doc/numpy-dev/user/quickstart.html]

Die Lösung bietet ein sog. _third party_ Bibliothek. Im Gegensatz zur Python Standardbibliothek werden third party Bibliotheken nicht mit jeder Python installation mit installiert sondern man muss sie zusätzlich von Hand dazu installieren.  

Praktischerweise bringen viele wissenschaftliche Python-Distributionen (wie z.B. die von Anaconda) schon sehr viele von den wichtigen third party Bibliotheken mit. Auch unsere hier benutzte Programmierumgebung kennt sie schon.  

Die Bibliothek, die wir für mehrdimensionale Listen, sog. _arrays_ brauchen, inst ```NumPy``` (für numeric Python). Ganz gleich wie Module aus der Standardbibliothek, können wir NumPy einfach importieren:

In [56]:
# das keyword 'as' gibt numpy beim Import ein
# anderes Kürzel um auf die Funktionalität zuzugreifen.
# Das tun wir, um weniger Tippen zu müssen.
import numpy as np

In [75]:
# konvertiere die Liste von Listen A mit der 
# asarray() Funktion in ein NumPy Array
B = np.asarray(A)

# zum Vergleich geben wir A und B noch einmal aus
print('Liste von Listen:\n {}\n'.format(A))
print('NumPy nD-Array:\n {}'.format(B))

Liste von Listen:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

NumPy nD-Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Auf Elemente in mehrdimensionalen Arrays greifen wir mit Hilfe von mehreren Indices zu (ein Index pro Dimension des Arrays um das Element zweifelsfrei zu lokalisieren):

In [74]:
print(B[1,1])

5


Macht erstmal nicht viel her, aber schon die eingebaute slicing Funktionalität ist wirklich praktisch, denn wir können jetzt slices über mehrere Dimensionen definieren:

In [76]:
print(B[0:2, 0:2])  # [reihe, spalte]

[[1 2]
 [4 5]]


In [78]:
print(B[0:, 0:2])  # [reihe, spalte]

[[1 2]
 [4 5]
 [7 8]]


In [80]:
print(B[0:2, 0:])  # [reihe, spalte]

[[1 2 3]
 [4 5 6]]


**WICHTIG:** Bei der Reihenfolge der Indices gilt der Merksatz:  
_Zeile zuerst, Spalte später!_

[top](#top)

<a name="erstellen"></a>Arrays erstellen
---

Um Arrays zu erstellen gibt es neben ```asarray()``` zum konvertieren anderer Kontainer in Arrays noch viele andere Funktionen. Drei hilfreiche davon sind:

* ```arange()```: gleich wie ```range()```, nur dass direkt ein Array erstellt wird.
* ```reshape()```: verändert die Form eines Arrays.
* ```linspace()```: ähnlich zu ```arange()``` aber erzeugt keine Ganzzahlen sondern eine lineare Interpolation zwischen Start und Ende.

In [84]:
# erstelle ein eindimensionales Array mit 16 Elementen
A = np.arange(16)
print(A)
print(type(A))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>


In [87]:
# forme A in ein zweidimensionales 4x4 Array um
A = A.reshape((4,4))
print(A)

# merke: die Gesamtzahl der Elemente muss dabei
# erhalten bleiben!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [105]:
start = 0
stop = 10
anzahl = 50

# linspace erzeugt "anzahl" Elemente die gleichmäßig
# zwischen start und stop verteilt werden
B = np.linspace(start, stop, anzahl)  # (start, stop, anzahl)

print(B)

[  0.           0.20408163   0.40816327   0.6122449    0.81632653
   1.02040816   1.2244898    1.42857143   1.63265306   1.83673469
   2.04081633   2.24489796   2.44897959   2.65306122   2.85714286
   3.06122449   3.26530612   3.46938776   3.67346939   3.87755102
   4.08163265   4.28571429   4.48979592   4.69387755   4.89795918
   5.10204082   5.30612245   5.51020408   5.71428571   5.91836735
   6.12244898   6.32653061   6.53061224   6.73469388   6.93877551
   7.14285714   7.34693878   7.55102041   7.75510204   7.95918367
   8.16326531   8.36734694   8.57142857   8.7755102    8.97959184
   9.18367347   9.3877551    9.59183673   9.79591837  10.        ]


Zusätzlich dazu können wir Arrays auch aus Dateien laden bzw. sie als Dateien speichern mit
* ```np.loadtxt()```
* ```np.savetxt()```

In [108]:
polygone = np.loadtxt('polygons.txt')
print(polygone)

[[ 2.93524537  2.9328648   2.93049891 ...,         nan         nan
          nan]
 [ 2.934738    2.93261704  2.93027465 ...,         nan         nan
          nan]
 [ 2.93613947  2.93298815  2.9306612  ...,         nan         nan
          nan]
 ..., 
 [ 2.962692    2.962387    2.963455   ...,  3.007614    3.003555    2.99913   ]
 [ 2.960098    2.959122    2.963394   ...,  3.012039    3.011398    3.010513  ]
 [ 2.960251    2.958511    2.961594   ...,  3.009201    3.011093    3.009872  ]]


Wenn ein Array zu groß ist, um es sinnvoll auszugeben, dann hilft uns ein sogenanntes _Attribut_ des Array-Objektes weiter, ```shape```:

In [110]:
print(polygone.shape)

(1091, 1051)


In [114]:
# shape ist ein Tupel, ein iterierbarer Kontainer
# ähnlich einer Liste, und hat zwei Elemente die
# wir einzelnen Variablen zuweisen können
hoehe, breite = polygone.shape

print('Anzahl Zeilen: {}'.format(hoehe))
print('Anzahl Spalten: {}'.format(breite))

Anzahl Zeilen: 1091
Anzahl Spalten: 1051


Ähnlich einfach können wir Matrizen aus Variablen in Dateien schreiben und speichern:

In [115]:
np.savetxt('matrix_c.txt', C)

[top](#top)

<a name="mathe"></a>Mathe mit Arrays
---

Führen wir Standardoperationen wie plus, minus, mal oder geteilt auf Arrays aus, werden diese _elementeweise_ auf jeden Eintrag im Array angewendet:

In [99]:
A = np.arange(16).reshape((4,4))

print('vorher:')
print(A)
A = A + 2
print('\nnachher:')
print(A)

vorher:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

nachher:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


Zum Vergleich: mit Listen funktioniert das nicht!

In [100]:
a = [1, 2, 3, 4]
a + 2

TypeError: can only concatenate list (not "int") to list

Auch ganz einfach mittels ```dot()``` Funktion zu realisieren ist die Matrix-Multiplikation:

In [102]:
# erstelle zwei 3x3 Matrizen aus Listen
A = np.asarray([[1, 2, 3], [0, 1, 0], [2, 0, 1]])
B = np.asarray([[3, 0, 4], [0, 0, 1], [2, 2, 2]])

# multipliziere die Matrizen und speichere das Ergebnis
C = np.dot(A, B)

# überprüfe den Output
print('A:')
print(A)
print('\nB:')
print(B)
print('\nC:')
print(C)

A:
[[1 2 3]
 [0 1 0]
 [2 0 1]]

B:
[[3 0 4]
 [0 0 1]
 [2 2 2]]

C:
[[ 9  6 12]
 [ 0  0  1]
 [ 8  2 10]]


[top](#top)

<a name="filter"></a>Filter
---

Wir können auch logische Funktionen auf Arrays anwenden und sie damit _filtern_. Die entsprechende Funktion dafür ist ```where()```:

In [118]:
# an welchen Indices in der Matrix C ist die
# Bedingung Element < 10 erfüllt?
np.where(C < 10)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 1, 0, 1, 2, 0, 1]))

In [120]:
# welche Einträge in C sind kleiner C?
C[np.where(C < 10)]

array([9, 6, 0, 0, 1, 8, 2])

In [121]:
# filtert die Matrix C so, dass jedes
# Element größer 10 auf 1 gesetzt wird
# und jedes Element kleiner 10 auf null
C = np.where(C < 10, 0, 1)
print(D)

[[9 6 0]
 [0 0 1]
 [8 2 0]]


[top](#top)

<a name="uebung07"></a>Übung 07: Matrizen
===

1. **Matrizen**
  1. Erstelle eine Liste mit 100 zufälligen Ganzzahlen. Konvertiere die Liste in ein NumPy Array und forme sie in eine 10 x 10 Matrix um.
  2. Speichere die Matrix in einer Textdatei.
  3. **(Optional)** Recherchiere, wie man die selbe Aufgabe mit ```numpy.random.randint()``` wesentlich kürzer schreiben kann.
  4. Weise die 5x5 sub-Matrizen oben links, oben rechts, unten links und unten rechts jeweils separaten Variablen zu. 
  5. Multipliziere die sub-Matrizen miteinander und gib das Ergebnis aus.
  6. **(Optional)** Experimentiere ein bisschen mit der Filter-Funktion ```where()```. Andere logische Abfragen und Operationen? Elemente aus zwei Matrizen einer dritten zuweisen?

[top](#top)